- name: Monitor CPU and Memory
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy monitoring script
      copy:
        src: ../scripts/check_usage.py
        dest: /tmp/check_usage.py
        mode: '0755'

    - name: Run the script and capture output
      command: python3 /tmp/check_usage.py {{ check_type }}
      register: result
      ignore_errors: false

    - name: Save output to local file (on GitHub runner)
      copy:
        content: "{{ result.stdout }}"
        dest: "../ansible/results/{{ inventory_hostname }}.txt"
      delegate_to: localhost
